name: 'Site Deploy'
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        env:
          GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
        run: |
          mkdir readme
          cp README.md readme/README.md
          cd readme
          git config --global user.email "afanyiyu@hotmail.com"
          git config --global user.name "AllQuire Site Deploy Bot"
          git init
          git add -A
          git commit -m 'chore':' 🤖 GitHub Pages Deploy'
          git push -f https://${GITHUB_DEPLOY_TOKEN}@github.com/allquire/allquire.github.io.git master
